import slugify from "react-slugify";

export const events = [
  {
    id: 1,
    title: "One Ok Rock Detox",
    date: "2026-02-21",
    stadium: "Impact Arena",
    imageUrl: "/images/oneOKrock.jpg",
    ticketUrl: "",
    slug: slugify("One Ok Rock Detox"),
  },
  {
    id: 2,
    title: "One Ok Rock Detox",
    date: "2026-02-21",
    stadium: "Impact Arena",
    imageUrl: "/images/oneOKrock.jpg",
    ticketUrl: "",
    slug: slugify("One Ok Rock Detox"),
  },
  {
    id: 3,
    title: "One Ok Rock Detox",
    date: "2026-02-21",
    stadium: "Impact Arena",
    imageUrl: "/images/oneOKrock.jpg",
    ticketUrl: "",
    slug: slugify("One Ok Rock Detox"),
  },
  {
    id: 4,
    title: "One Ok Rock Detox",
    date: "2026-02-21",
    stadium: "Impact Arena",
    imageUrl: "/images/oneOKrock.jpg",
    ticketUrl: "",
    slug: slugify("One Ok Rock Detox"),
  },
];

export const upcomingShows = [
  {
    title: "One Ok Rock Detox",
    date: "2026-02-21",
    stadium: "Impact Arena",
    imageUrl: "/images/oneOKrock.jpg",
    ticketUrl: "",
    slug: slugify("One Ok Rock Detox"),
  },
  {
    title: "One Ok Rock Detox",
    date: "2026-02-21",
    stadium: "Impact Arena",
    imageUrl: "/images/oneOKrock.jpg",
    ticketUrl: "",
    slug: slugify("One Ok Rock Detox"),
  },
  {
    title: "One Ok Rock Detox",
    date: "2026-02-21",
    stadium: "Impact Arena",
    imageUrl: "/images/oneOKrock.jpg",
    ticketUrl: "",
    slug: slugify("One Ok Rock Detox"),
  },
  {
    title: "One Ok Rock Detox",
    date: "2026-02-21",
    stadium: "Impact Arena",
    imageUrl: "/images/oneOKrock.jpg",
    ticketUrl: "",
    slug: slugify("One Ok Rock Detox"),
  },
  {
    title: "One Ok Rock Detox",
    date: "2026-02-21",
    stadium: "Impact Arena",
    imageUrl: "/images/oneOKrock.jpg",
    ticketUrl: "",
    slug: slugify("One Ok Rock Detox"),
  },
  {
    title: "One Ok Rock Detox",
    date: "2026-02-21",
    stadium: "Impact Arena",
    imageUrl: "/images/oneOKrock.jpg",
    ticketUrl: "",
    slug: slugify("One Ok Rock Detox"),
  },
];
